# Generated by Django 3.2.6 on 2021-09-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_inventory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
